/* -------------------------------------------------------------
# Autor: 	Osni Teodoro de Souza Júnior
# Objetivo: Carga de dados para tabela sobrenome
-------------------------------------------------------------*/

INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Fernandes','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Martins','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Mendes','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Caldeira','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Cunha','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Neves','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Pinto','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Cavalcanti','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Viana','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Costela','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Peixoto','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Barbosa','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Fernandes','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Ramos','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Alves','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Lopes','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Pires','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Cardoso','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Sousa','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Souza','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Carvalho','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Martins','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Ribeiro','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Porto','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Moraes','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Paulino','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Teixeira','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Viana','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Fagundes','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Vieira','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Rosa','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Bragança','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Fogaça','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Santos','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Duarte','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Limeira','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('da Paz','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Antonino'	,'BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('da Costa','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Lopes','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Pereira','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Silveira','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('das Neves','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Rezende','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Melo','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Bernardes','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Franco','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Pereira','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Rocha','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Araújo','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Porto','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Gonçalves','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Aragão','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Sales','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Dias','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Barbosa','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Azevedo','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Farias','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Monteiro','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Pedreiro','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Gonçalves','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Cunha','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Rodrigues','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('da Conceição','BRA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Novaes','BRA');

-- USA
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Barton','USA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Green','USA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Gonzales','USA'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Gray','USA'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Williams','USA'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Maddox','USA'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Erickson','USA'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Rhodes','USA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Adkins','USA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Turner','USA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Clark','USA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Powell','USA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('George','USA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Ford','USA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Mcbride','USA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Morton','USA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Stone','USA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Greene','USA');

-- Italianos
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Ferrucci','ITA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Stradivari','ITA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Versace','ITA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Monduzzi','ITA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Toscani','ITA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Nespoli','ITA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Nespolo','ITA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Callegari','ITA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Pezzali','ITA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Notarbartolo','ITA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Ricciardi','ITA');

-- Espanhóis
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Donaire','SPA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Solsona','SPA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('del Bellido','SPA');

INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Mínguez','SPA');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Gutiérrez','SPA');

-- Africanos
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Dlamini','AFR');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Nkosi','AFR');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Ndlovu','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Khumalo','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Sithole','AFR');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Botha','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Mahlangu','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Mokoena','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Smith','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Naidoo','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Mkhize','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Mthembu','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Ngcobo','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Gumede','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Jacobs','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Buthelezi','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Zulu','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Nel','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Pretorius','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Venter','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Khoza','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Coetzee','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Fourie','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Sibiya','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Van wyk','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Du plessis','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Govender','AFR');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Mofokeng','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Mhlongo','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Pillay','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Baloyi','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Mbatha','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Smit','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Radebe','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Kruger','AFR');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Mathebula','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Ntuli','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Zwane','AFR');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Mazibuko','AFR');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Williams','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Tshabalala','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Van zyl','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Nxumalo','AFR');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Chauke','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Ngwenya','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Cele','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Du toit','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Van der merwe','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Mthethwa','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Erasmus ','AFR');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Louw','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Ngobeni','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Van niekerk','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Joubert','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Meyer','AFR');
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Steyn','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Ngubane','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Maluleke','AFR'); 
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Maseko','AFR');  
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Molefe','AFR');  
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Mtshali','AFR');  
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Mabaso','AFR');  
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Marais','AFR');  
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Viljoen','AFR');  
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Potgieter','AFR');  
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Dube','AFR');  
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Swanepoel','AFR');  
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Swart','AFR');  
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Mkhwanazi','AFR');  
INSERT INTO pessoa.sobrenome(surname, tiponac) VALUES ('Mnisi','AFR');


